# Rationale: Using Docker Compose simplifies local development by containerizing
# dependencies. This ensures that every developer runs the same database version
# with the same initial state, eliminating "it works on my machine" issues.
version: '3.8'

services:
  postgres-auth:
    image: postgres:15-alpine
    container_name: postgres-auth-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres-auth-data: