# A descriptive name for your workflow
name: CI Pipeline

# Controls when the workflow will run
on:
  push:
    branches: [main, homologation, development]
  pull_request:
    branches: [main, homologation, development]
  workflow_dispatch:

jobs:
  # This job validates code quality with linting and unit tests
  validate:
    runs-on: ubuntu-latest

    # Set a default working directory for all 'run' steps in this job
    defaults:
      run:
        working-directory: ./main-app

    steps:
      # Step 1: Checkout the main application code
      - name: Checkout application code
        uses: actions/checkout@v4
        with:
          path: main-app

      # Step 2: Setup Node.js environment with caching for speed
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'main-app/package-lock.json'

      # Step 3: Install application dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run the linter
      - name: Run lint check
        run: npm run lint

      # Step 5: Run the unit tests
      - name: Run unit tests
        run: npm run test
