# A descriptive name for your workflow
name: CI Pipeline

# Controls when the workflow will run
on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    # Set a default working directory for all 'run' steps in this job.
    # This avoids repeating 'working-directory:' in most steps.
    defaults:
      run:
        working-directory: ./main-app

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: auth_db_test
        # The health check is crucial: it ensures the DB is ready before steps run.
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432

    steps:
      # Step 1: Checkout the main application code into the 'main-app' directory
      - name: Checkout application code
        uses: actions/checkout@v4
        with:
          path: main-app

      # Step 2: Checkout the public configuration repository into the 'config' directory
      - name: Checkout config repository
        uses: actions/checkout@v4
        with:
          repository: brunosilveiradosanjos/apl-ms-auth-config
          path: config

      # Step 3: Manually download and install the latest versions of sops, age, and yq
      # This step uses your original, trusted script for tool setup.
      - name: Setup SOPS, age, and yq
        # This step must run from the root, so we override the job's default working directory.
        working-directory: ./
        run: |
          # Install SOPS
          SOPS_VERSION=$(curl -s "https://api.github.com/repos/getsops/sops/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")' | sed 's/v//')
          wget "https://github.com/getsops/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.amd64"
          sudo mv "sops-v${SOPS_VERSION}.linux.amd64" /usr/local/bin/sops
          sudo chmod +x /usr/local/bin/sops
          # Install age
          AGE_VERSION=$(curl -s "https://api.github.com/repos/FiloSottile/age/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")' | sed 's/v//')
          wget "https://github.com/FiloSottile/age/releases/download/v${AGE_VERSION}/age-v${AGE_VERSION}-linux-amd64.tar.gz"
          tar -xzf "age-v${AGE_VERSION}-linux-amd64.tar.gz"
          sudo mv age/age /usr/local/bin/
          sudo mv age/age-keygen /usr/local/bin/
          # Install yq
          YQ_VERSION=$(curl -s "https://api.github.com/repos/mikefarah/yq/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")' | sed 's/v//')
          wget "https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_amd64"
          sudo mv yq_linux_amd64 /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      # Step 4: Decrypt secrets and export them as environment variables for the job
      - name: Decrypt and Export Secrets
        working-directory: ./
        run: |
          sops --decrypt config/development/config.yml | \
          yq -r 'to_entries | .[] | .key + "=" + "\"" + .value + "\""' >> $GITHUB_ENV
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

      # Step 5: Override variables for the CI environment
      - name: Override DB Host and Set Node Env for CI
        working-directory: ./
        run: |
          echo "DB_HOST=postgres" >> $GITHUB_ENV
          echo "NODE_ENV=ci" >> $GITHUB_ENV

      # Step 6: Setup Node.js environment with caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'main-app/package-lock.json'

      # Step 7: Install application dependencies (runs in ./main-app due to defaults)
      - name: Install dependencies
        run: npm ci

      # Step 8: Run the linter
      - name: Run lint check
        run: npm run lint

      # Step 9: Run the unit tests
      - name: Run unit tests
        run: npm test

      # Step 10: Run the end-to-end tests
      - name: Run E2E tests
        run: npm run test:e2e:run
